# Generated by Django 5.0.6 on 2024-07-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('month', 'year')},
        ),
    ]
