# Generated by Django 5.0.6 on 2024-07-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(),
        ),
    ]
